baseURL = "https://mindflakes.com/"
languageCode = "en-us"
copyright = "Copyright Nelson Chen"
title = "mindflakes"
theme = "mindflakes-refresh"

metaDataFormat = "yaml"

[pagination]
pagerSize = 10
path = "page"

[author]
name = "Nelson Chen"

[permalinks]
posts = "posts/:year/:month/:day/:slug/"

[params]
searchEngineURL = "https://www.google.com/search"
sidebarHeader = "Hello there!"
description = "Nelson Chen's blog and project notes."

sidebarText = """
This is a site for stuff I write that doesn't fit in 280 characters or simple images.
"""

truncate = false

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[[menu.main]]
Name = "Blog"
URL = "/"
weight = -10

[[menu.main]]
Name = "Projects"
URL = "/projects"
weight = -9

[[menu.main]]
Name = "GitHub"
URL = "https://github.com/nelsonjchen"
weight = -5

[[menu.main]]
Name = "Mastodon"
URL = "https://mastodon.social/@crazysim"
weight = 0
